### ISSUE TITLE
Android: Move uses-permission tag outside of application

### ISSUE THREAD

**Issue by Jemesson** [marlonchalegre/grocery_store#1]
## AndroidManifest.xml
```xml 
   <uses-permission android:name="android.permission.INTERNET" />

   <application
        android:label="grocery_store"
        android:icon="@mipmap/ic_launcher">
```

**Comment by marlonchalegre** [comment]
Abre um PR :)

**Comment by Jemesson** [comment]
Fala mestre. Não deixou eu fazer um push em uma branch nova.

Em sex., 24 de set. de 2021 às 11:02, Marlon Chalegre <
***@***.***> escreveu:

**Comment by marlonchalegre** [comment]
Faz fork e abre um PR vindo do teu Fork

**Comment by Jemesson** [comment]
Got it, thanks!

Em sex., 24 de set. de 2021 às 14:55, Marlon Chalegre <
***@***.***> escreveu:

**Comment by Jemesson** [comment]
Done. https://github.com/marlonchalegre/grocery_store/pull/2

**Comment by Jemesson** [comment]
Closing the issue ✅
